# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('food_type', models.CharField(choices=[('VEGE', 'Vegetables'), ('SEAFOOD', 'Seafood'), ('MEAT', 'Meat'), ('COOKED', 'Cooked'), ('FRUIT', 'Fruit'), ('BAKERY', 'Bakery Items'), ('PASTA_RICE', 'Pasta & Rice'), ('DRIED', 'Dried food'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('allergens', models.CharField(choices=[('NUTS', 'Nuts'), ('GLUTEN', 'Gluten'), ('NON_VEGAN', 'Non-Vegan'), ('SEAFOOD', 'Seafood'), ('EGGS', 'Eggs')], default=None, max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=50)),
                ('picture', models.FileField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('food_listed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Food')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='backend.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='backend.User'),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set([('food_name', 'quantity')]),
        ),
    ]
