# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('date_listed', models.DateField(auto_now=True)),
                ('food_type', models.CharField(choices=[('VEGE', 'Vegetables'), ('SEAFOOD', 'Seafood'), ('MEAT', 'Meat'), ('COOKED', 'Cooked'), ('FRUIT', 'Fruit'), ('BAKERY', 'Bakery Items'), ('PASTA_RICE', 'Pasta & Rice'), ('DRIED', 'Dried food'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('allergens', models.CharField(choices=[('NUTS', 'Nuts'), ('GLUTEN', 'Gluten'), ('NON_VEGAN', 'Non-Vegan'), ('SEAFOOD', 'Seafood'), ('EGGS', 'Eggs'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('picture', models.TextField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=500)),
                ('created_at', models.CharField(default=b'2017-04-22 16:31:03.407953', max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('VEGE', 'Vegetables'), ('SEAFOOD', 'Seafood'), ('MEAT', 'Meat'), ('COOKED', 'Cooked'), ('FRUIT', 'Fruit'), ('BAKERY', 'Bakery Items'), ('PASTA_RICE', 'Pasta & Rice'), ('DRIED', 'Dried food'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('preference_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('preference', 'preference_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set([('food_name', 'quantity')]),
        ),
    ]
