# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-04-22 16:31:34.899470', max_length=50),
        ),
    ]
