# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170309_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='location',
        ),
        migrations.AddField(
            model_name='food',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
