# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170325_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_content',
            field=models.TextField(default=''),
        ),
    ]
