# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_message_msg_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-26 20:29:00.642777', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(max_length=500),
        ),
    ]
