# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_message_created_at'),
        ('backend', '0008_auto_20170326_2029'),
    ]

    operations = [
    ]
