# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_merge_20170327_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-27 12:56:50.168230', max_length=50),
        ),
    ]
