# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20170327_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='allergens',
            field=models.CharField(choices=[('NUTS', 'Nuts'), ('GLUTEN', 'Gluten'), ('NON_VEGAN', 'Non-Vegan'), ('SEAFOOD', 'Seafood'), ('EGGS', 'Eggs'), ('NONE', 'None')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-27 16:44:47.342715', max_length=50),
        ),
    ]
