# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20170327_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='allergens',
            field=models.CharField(choices=[('NUTS', 'Nuts'), ('GLUTEN', 'Gluten'), ('NON_VEGAN', 'Non-Vegan'), ('SEAFOOD', 'Seafood'), ('EGGS', 'Eggs'), ('NONE', 'None')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-27 16:45:51.283095', max_length=50),
        ),
    ]
