# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20170328_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-28 15:00:10.079024', max_length=50),
        ),
    ]
