# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20170328_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-28 16:03:21.320089', max_length=50),
        ),
    ]
