# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0018_auto_20170330_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('VEGE', 'Vegetables'), ('SEAFOOD', 'Seafood'), ('MEAT', 'Meat'), ('COOKED', 'Cooked'), ('FRUIT', 'Fruit'), ('BAKERY', 'Bakery Items'), ('PASTA_RICE', 'Pasta & Rice'), ('DRIED', 'Dried food'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('preference_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-03-31 20:47:01.146602', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('preference', 'preference_user')]),
        ),
    ]
