# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20170331_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-04-07 10:39:45.579451', max_length=50),
        ),
    ]
