# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20170407_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='food',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-04-07 13:12:15.688820', max_length=50),
        ),
    ]
