# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20170407_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.CharField(default=b'2017-04-08 16:23:28.993045', max_length=50),
        ),
    ]
